In [1]:
import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport
import sweetviz as sv

In [2]:
df = pd.read_csv("7. Udemy Courses.csv")

In [3]:
df.head(5)

,course_id,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,288942,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,1170074,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,1193886,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,1116700,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,1120410,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments

In [4]:
#satırlarda ve sütunlrda null değerlerini kontrul etme :
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3682 entries, 0 to 3681
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3682 non-null   int64
 1   course_title         3682 non-null   object
 2   is_paid              3682 non-null   bool
 3   price                3682 non-null   object
 4   num_subscribers      3682 non-null   int64
 5   num_reviews          3682 non-null   int64
 6   num_lectures         3682 non-null   int64
 7   level                3682 non-null   object
 8   content_duration     3682 non-null   object
 9   published_timestamp  3682 non-null   object
 10  subject              3682 non-null   object
dtypes: bool(1), int64(4), object(6)
memory usage: 291.4+ KB

In [5]:
#course_id sütunu silme :
df.drop("course_id",axis=1,inplace=True)

In [6]:
df.head(5)

,course_title,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5 hours,2014-09-18T05:07:05Z,Musical Instruments
1,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1 hour,2017-04-12T19:06:34Z,Musical Instruments
2,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5 hours,2017-04-26T18:34:57Z,Musical Instruments
3,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1 hour,2017-02-21T23:48:18Z,Musical Instruments
4,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37 mins,2017-02-21T23:44:49Z,Musical Instruments

In [7]:
#is_paid sütunu Ture ,false değerlerinden Yes ,No değerlerine değiştirme :
#df['is_paid'] = df['is_paid'].astype('object')
#df['is_paid'] = df['is_paid'].replace(['True'], pice sütunun tipi object'ten int64'e değiştirme ve free kalemesi yerinde 0 değeri gösterme:'yer')

In [8]:
df['price'] = df['price'].replace(['Free'],0)
df['price'] = df['price'].astype('int64')

In [9]:
df['content_duration'] = [x.replace('hours', '').replace('hour', '').replace('mins', '').replace('questions', '')for x in df['content_duration']]
df['content_duration'] = df['content_duration'].astype(str).astype(float)

In [10]:
df['published_timestamp']= pd.to_datetime(df['published_timestamp'])

In [11]:
df.columns=['Kurs başlığı','Ödenmiş kurs','Fıyat','Obune sayısı','Görüntülme Sayısı','Ders Sayısı','Seviye','İçerik Süresi','yayınlanan zaman damgası','Kursun konusu']

In [12]:
df.head(10)

,Kurs başlığı,Ödenmiş kurs,Fıyat,Obune sayısı,Görüntülme Sayısı,Ders Sayısı,Seviye,İçerik Süresi,yayınlanan zaman damgası,Kursun konusu
0,#1 Piano Hand Coordination: Play 10th Ballad i...,True,35,3137,18,68,All Levels,1.5,2014-09-18 05:07:05+00:00,Musical Instruments
1,#10 Hand Coordination - Transfer Chord Ballad ...,True,75,1593,1,41,Intermediate Level,1.0,2017-04-12 19:06:34+00:00,Musical Instruments
2,#12 Hand Coordination: Let your Hands dance wi...,True,75,482,1,47,Intermediate Level,1.5,2017-04-26 18:34:57+00:00,Musical Instruments
3,#4 Piano Hand Coordination: Fun Piano Runs in ...,True,75,850,3,43,Intermediate Level,1.0,2017-02-21 23:48:18+00:00,Musical Instruments
4,#5 Piano Hand Coordination: Piano Runs in 2 ...,True,75,940,3,32,Intermediate Level,37.0,2017-02-21 23:44:49+00:00,Musical Instruments
5,#6 Piano Hand Coordination: Play Open 10 Balla...,True,65,2015,3,21,Intermediate Level,44.0,2017-03-08 17:53:36+00:00,Musical Instruments
6,#7 Piano Hand Coordination: Play Piano Runs in...,True,65,2015,2,25,Intermediate Level,1.0,2017-03-08 18:09:32+00:00,Musical Instruments
7,* An Integrated Approach to the Fundamentals o...,True,200,134,14,123,All Levels,5.5,2016-03-15 17:23:07+00:00,Business Finance
8,:::Beginners Guide To Creating Amazing Images ...,True,25,72,5,17,Beginner Level,1.0,2014-04-29 19:50:31+00:00,Graphic Design
9,[Value Investing] Where White People Keep Thei...,True,200,2715,70,20,Expert Level,4.0,2016-05-25 21:04:41+00:00,Business Finance

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3682 entries, 0 to 3681
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Kurs başlığı              3682 non-null   object
 1   Ödenmiş kurs              3682 non-null   bool
 2   Fıyat                     3682 non-null   int64
 3   Obune sayısı              3682 non-null   int64
 4   Görüntülme Sayısı         3682 non-null   int64
 5   Ders Sayısı               3682 non-null   int64
 6   Seviye                    3682 non-null   object
 7   İçerik Süresi             3682 non-null   float64
 8   yayınlanan zaman damgası  3682 non-null   datetime64[ns, UTC]
 9   Kursun konusu             3682 non-null   object
dtypes: bool(1), datetime64[ns, UTC](1), float64(1), int64(4), object(3)
memory usage: 262.6+ KB